config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get 'stats' => "home#stats"
  post 'shorten' => "home#shorten"
  get ':id' => "home#decrypt_url"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stat.rb
class Stat < ApplicationRecord
  belongs_to :url
end

app/models/url.rb
class Url < ApplicationRecord
  has_many :stats
  before_create :add_short_url

  def add_short_url
    self.short_url = SecureRandom.alphanumeric(5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
require 'securerandom'
class HomeController < ApplicationController

  def index
  end


  def stats
    @urls = Url.includes(:stats).all
  end

  def shorten
    url = Url.create(full_url: params[:url], expires_at: Time.now + 1.month)
    @shorterned_url =  "http://localhost:3001/#{url.short_url}"
    respond_to do |format|
      format.turbo_stream
    end
  end

  def decrypt_url
    url = Url.find_by(short_url: params[:id])
    if url.present? && url.expires_at > Time.now
      url.update(click: url.click.to_i + 1)
      ip = request.ip
      url.stats.create(ip: ip, country: Geocoder.search(ip).first.country)
      redirect_to url.full_url, allow_other_host: true
    else
      render :file => "#{Rails.root}/public/404.html"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_short_url.html.erb
<div id="short_url">
  <hr/>
  Here's your short url!
  <p></p>
  <%= shorterned_url %>
</div>

app/views/home/index.html.erb
<h2>Welcome to short.com</h2>
<%= form_tag(shorten_path, remote: true) do |f|%>
 <%= label_tag 'Please enter your url here'%>
 <%= text_field_tag :url, "", required: true%>
 <%= submit_tag :shorten%>
<%end%>

<p></p>

<div id="short_url">
</div>

app/views/home/shorten.turbo_stream.erb
<%= turbo_stream.append "short_url", partial: "short_url", locals: { shorterned_url: @shorterned_url } %>

app/views/home/stats.html.erb
<h2>Analytics</h2>

<br/>

<% @urls.each do |url|%>
  <b><%= url.full_url %></b><br/>
  <%= "http://localhost:3001/" + url.short_url %>
  <br/>
  <br/>
  Total Clicks: <%= url.click %> <br/>
  Top Countries: <%= url.stats.group(:country).order("count(stats.id) DESC").limit(3).map(&:country).join(",")%>
  <hr/>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortenUrl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>